// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtMiaMkyME6Iqsi3H-v24kW0VKHfO3_g',
    appId: '1:828569241123:web:f247edc4c94554d2009396',
    messagingSenderId: '828569241123',
    projectId: 'servicesphere-55222',
    authDomain: 'servicesphere-55222.firebaseapp.com',
    storageBucket: 'servicesphere-55222.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5wwVe5xEyv4Hc3Kjs4MXjA50XXz0U-BA',
    appId: '1:828569241123:android:a334a1292ebe8b34009396',
    messagingSenderId: '828569241123',
    projectId: 'servicesphere-55222',
    storageBucket: 'servicesphere-55222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDle3WLiKvLCC1oB_3gRzjJF-VE0zUsyJQ',
    appId: '1:828569241123:ios:aa6957dc3a7d4843009396',
    messagingSenderId: '828569241123',
    projectId: 'servicesphere-55222',
    storageBucket: 'servicesphere-55222.appspot.com',
    iosBundleId: 'com.example.serviceSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDle3WLiKvLCC1oB_3gRzjJF-VE0zUsyJQ',
    appId: '1:828569241123:ios:f11493255f1a7ebe009396',
    messagingSenderId: '828569241123',
    projectId: 'servicesphere-55222',
    storageBucket: 'servicesphere-55222.appspot.com',
    iosBundleId: 'com.example.serviceSphere.RunnerTests',
  );
}
